### ISSUE TITLE
Initializing I/O drivers

### ISSUE THREAD

**Issue by cswrd** [ev3osek/ev3osek#2]
c577b90 Initializing I/O only works when it is done from a task. If it is done within the OSEK startup hook routine there are failures regarding returning from functions.

**Comment by cswrd** [comment]
c577b90 has a workaround. The init for I/O drivers is done at first soon as a first ECRobot function call occurs. Still init is also done within the OSEK startup hook routine to use the timer interrupt.

**Comment by AchimStuy** [comment]
Solved in commit e19c36e.
