### ISSUE TITLE
Pre and post task hooks

### ISSUE THREAD

**Issue by cswrd** [ev3osek/ev3osek#5]
OSEK allows users to define pre and post task hooks. c577b90 Currently it isn't supported because linking doesn't work if the user doesn't use those functions. Hence this feature is currently not supported. Maybe one can create a c file that contains #defines with these functions without any implementation code. Those defines would only be used, if the user doesn't implement the hook routines. Then linking should always work correct.

**Comment by AchimStuy** [comment]
Implemented workaround in commit e19c36e.
